#! /usr/bin/bash
. ./mainMenu 
. ./TableMenu





function mainManu (){
echo "Select an option:"
select choice in "Create Database" "List Database" "Connect To Database" "Drop Database" "EXIT"; 
do
case $choice in
        "Create Database")
         createDataBase
         mainManu

            ;;
        "List Database")
          listDataBase
           mainManu
            ;;
        "Connect To Database")

	ConnectToDB
	mainManu
            ;;
        "Drop Database")
         DropDatabase
         mainManu
            ;;
        "EXIT")  
        break
            ;;
        *)
	"Not Valid Option"

            ;;
    esac
done
}

mainManu
