#! /usr/bin/bash
shopt -s extglob

function createDataBase(){
read -p "Please Enter Database name: " Dname
if [[ -d $Dname ]]
then
echo Database is already exist
elif [[ ! "$Dname" =~ ^[a-zA-Z0-9_[:space:]]+$ ]];
then
echo "Error: Database name must only contain letters, numbers, and underscores."
else 
mkdir "$Dname"
echo Database is created 
fi
}
function listDataBase(){
find ~/Project -mindepth 1 -maxdepth 1 -type d -exec basename {} \;
}
# استخدمنا find عشان هي افضل من اللوب لما يكون عندي اسم مكون من جزئين "nada emam" ف بالتالي هي بتعرف تهندل المسافات
# استخدمنا mindepth مع  max عشان يحبلنا المجلدات الفرعيه بس يعني ميعرضليش بردو معاهم اسم Project واستخدمنا max عشان ميجبلناش المجلدت اللي جوا المجلدات الفرعيه 


